stages:
- base-containers
- build
- RADV

variables:
  CI_TRON_JOB_TEMPLATE_PROJECT_URL: https://gitlab.freedesktop.org/gfx-ci/ci-tron
  CI_TRON_JOB_TEMPLATE_COMMIT: c35924b0196f32309e72b3a8e45e7d45a0ab0a91  # WARNING: Remember to update the remote include too!

include:
  - remote: 'https://gitlab.freedesktop.org/gfx-ci/ci-tron/-/raw/c35924b0196f32309e72b3a8e45e7d45a0ab0a91/.gitlab-ci/dut.yml'


# Disable all unwanted pipelines
workflow:
  rules:
    # Do not run on tags
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

# Only run on the CI branch
.base-containers-rules:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "ci"'
      when: on_success
    - when: never

# Run on all other branches, but the CI one
.test-rules:
  variables:
    # Common test options
    ACO_DEBUG: validateir,validatera
  rules:
    - if: '$CI_COMMIT_REF_NAME == "ci"'
      when: never

    # Stable
    - if: '$CI_COMMIT_BRANCH == "steamos-24.11"'
      when: on_success
      variables:
        JUPITER_VERSION: "3.7"
        BASE_IMAGE_TAG: !reference [jupiter-3.7-base, variables, IMAGE_TAG]
        BASE_IMAGE: $CI_REGISTRY_IMAGE/jupiter-3.7-base:$BASE_IMAGE_TAG
        COMPILE_LIBDRM_WITH_MESA: "0"
        RADV_PERFTEST: "transfer_queue"
        GPU_VERSION_SUFFIX: -aco
        CI_TRON_KERNEL__URL: https://fs.mupuf.org/linux-6.6-b2c-radv-ci
        # CI_TRON_KERNEL_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-3.6/os/x86_64/linux-neptune-65-6.5.0.valve20-1-x86_64.pkg.tar.zst'
        # CI_TRON_FIRMWARE_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-3.6/os/x86_64/linux-firmware-neptune-jupiter.20231113.1-1-any.pkg.tar.zst'
        # CI_TRON_UCODE_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-3.6/os/x86_64/amd-ucode-jupiter.20231113.1-1-any.pkg.tar.zst'

    # Beta
    # TODO: Create a new container when 3.8 gets branched
    - if: '$CI_COMMIT_BRANCH == "steamos-25.8"'
      when: on_success
      variables:
        JUPITER_VERSION: "main"
        BASE_IMAGE_TAG: !reference [jupiter-main-base, variables, IMAGE_TAG]
        BASE_IMAGE: $CI_REGISTRY_IMAGE/jupiter-main-base:$BASE_IMAGE_TAG
        COMPILE_LIBDRM_WITH_MESA: "0"
        CI_TRON_RADV_PERFTEST: "transfer_queue,video_decode,video_encode"
        CI_TRON_KERNEL__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64
        CI_TRON_INITRAMFS__DEPMOD__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64.depmod.cpio.xz
        CI_TRON_INITRAMFS__GPU__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64.gpu.cpio
        CI_TRON_KERNEL_CMDLINE__LOAD_MODULES: 'modules_load=amdgpu'

    # Default to main
    - when: on_success
      variables:
        JUPITER_VERSION: "main"
        BASE_IMAGE_TAG: !reference [jupiter-main-base, variables, IMAGE_TAG]
        BASE_IMAGE: $CI_REGISTRY_IMAGE/jupiter-main-base:$BASE_IMAGE_TAG
        COMPILE_LIBDRM_WITH_MESA: "0"
        RADV_PERFTEST: "transfer_queue,video_decode,video_encode"
        CI_TRON_KERNEL__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64
        CI_TRON_INITRAMFS__DEPMOD__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64.depmod.cpio.xz
        CI_TRON_INITRAMFS__GPU__URL: https://fs.mupuf.org/radv/linux-6.15.9/linux-x86_64.gpu.cpio
        CI_TRON_KERNEL_CMDLINE__LOAD_MODULES: 'modules_load=amdgpu'
        # CI_TRON_KERNEL_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/linux-neptune-68-6.8.12.valve2-1-x86_64.pkg.tar.zst'
        # CI_TRON_FIRMWARE_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/linux-firmware-neptune-jupiter.20240917.1-2-any.pkg.tar.zst'
        # CI_TRON_UCODE_URL: 'https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/amd-ucode-neptune-jupiter.20240917.1-2-any.pkg.tar.zst'

.container-build:
  image: quay.io/buildah/stable
  timeout: 2h
  tags:
    - CI-gateway
    - cpu:cores:16+
  variables:
    # BASE_IMAGE:
    # IMAGE_NAME:
    # IMAGE_TAG:
    # BUILD_SCRIPT:
    IMAGE_LABEL: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  script: |
    set -eux

    buildah login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

    manifest=$(buildah manifest inspect $IMAGE_LABEL 2>&1) || true
    if [[ $manifest == *"manifest unknown"* ]]; then
        # Allow the from container to be located in a private project by allowing
        # the use of an alternative token
        if [ -n "${FROM_CONTAINER_REGISTRY_TOKEN:-}" ]; then
            buildah login -u gitlab-ci-token -p ${FROM_CONTAINER_REGISTRY_TOKEN} $CI_REGISTRY
        fi

        buildcntr=$(buildah from --isolation=chroot $BASE_IMAGE)
        buildmnt=$(buildah mount $buildcntr)

        # HACK: This line will ensure that all jobs have origin/ci's .valve-ci/ folder
        # added in the source tree, allowing access to the CI files without requiring
        # adding commits on top of the branch being tested
        dnf install -y git
        git fetch origin ci && git restore --source origin/ci .valve-ci

        buildah run --isolation chroot --env DEQP_BRANCH=${DEQP_BRANCH:-} --env VKD3D_PROTON_COMMIT=${VKD3D_PROTON_COMMIT:-} --env DEQP_COMMITS_TO_BACKPORT="${DEQP_COMMITS_TO_BACKPORT:-}" --env COMPILE_LIBDRM_WITH_MESA=${COMPILE_LIBDRM_WITH_MESA:-0} --volume $PWD:/app/ --workingdir /app $buildcntr bash $BUILD_SCRIPT

        buildah unmount $buildcntr
        buildah commit --format docker $buildcntr $IMAGE_LABEL
        buildah rm $buildcntr

        # Push to the local registry of the project
        buildah login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        buildah push $IMAGE_LABEL || buildah push $IMAGE_LABEL
    else
        echo "The image already exists, nothing to do :)"
    fi

# base-containers stage

.base-container-build:
  stage: base-containers
  extends:
    - .base-containers-rules
    - .container-build
  variables:
    IMAGE_NAME: $CI_JOB_NAME
    BUILD_SCRIPT: .valve-ci/base-container-build.sh

    # Use a read-only registry token to access the steamos image since the
    # job's one can't access the container registry of other private projects
    FROM_CONTAINER_REGISTRY_TOKEN: $STEAMOS_REGISTRY_TOKEN_RO

jupiter-3.7-base:
  extends:
    - .base-container-build
  variables:
    BASE_IMAGE: registry.gitlab.steamos.cloud/steam/steamos-docker-images/jupiter-3.7/base-devel:latest
    DEQP_BRANCH: a9f7069b9a5ba94715a175cb1818ed504add0107
    DEQP_COMMITS_TO_BACKPORT:
    VKD3D_PROTON_COMMIT: 59d6d4b5ed23766e69fe252408a3401d2fd52ce8
    IMAGE_TAG: "2025-05-27.1"

jupiter-main-base:
  extends:
    - .base-container-build
  variables:
    BASE_IMAGE: registry.gitlab.steamos.cloud/steam/steamos-docker-images/jupiter-main/base-devel:latest
    DEQP_BRANCH: db48c34bebaf3359453e44ab151a2ff9f9c58eb2
    DEQP_COMMITS_TO_BACKPORT:
    VKD3D_PROTON_COMMIT: 03cca4cd978e964bbb5d4bd0ba655ea80011d04f
    IMAGE_TAG: "2025-11-04.1"


# build stage

jupiter-mesa:
  stage: build
  extends:
    - .test-rules
    - .container-build
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
    IMAGE_NAME: jupiter-mesa-$JUPITER_VERSION
    BUILD_SCRIPT: .valve-ci/mesa-build.sh

# RADV stage

.ci-tron-job:
  stage: RADV
  dependencies: []
  extends:
    - .ci-tron-b2c-job-v1
    - .test-rules
  timeout: 3h10m
  artifacts:
    when: always
    paths:
      - "./"
    exclude:
      - storage   # Work around a b2c bug
      - .valve-ci
    expire_in: 1 week
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none

    # Save the job script so that it can be used for local testing and analysis when things go wrong
    CI_TRON_JOB_SCRIPT_PATH: "job_script.sh"

    CI_TRON_INITRAMFS__B2C__URL: 'https://gitlab.freedesktop.org/gfx-ci/boot2container/-/releases/v0.9.12.1/downloads/initramfs.linux_amd64.cpio.xz'
    CI_TRON_PATTERN__SESSION_END__REGEX: '^.*It''s now safe to turn off your computer\r$'
    CI_TRON_PATTERN__JOB_SUCCESS__REGEX: 'Execution is over, pipeline status: 0\r$'
    CI_TRON_PATTERN__JOB_WARN__REGEX: ''
    CI_TRON_PATTERN__SESSION_REBOOT__REGEX: 'GPU hang detected!'

    CI_TRON_TIMEOUT__BOOT_CYCLE__MINUTES: 180
    CI_TRON_TIMEOUT__BOOT_CYCLE__RETRIES: 1
    CI_TRON_TIMEOUT__FIRST_CONSOLE_ACTIVITY__MINUTES: 2
    CI_TRON_TIMEOUT__FIRST_CONSOLE_ACTIVITY__RETRIES: 3
    CI_TRON_TIMEOUT__CONSOLE_ACTIVITY__MINUTES: 3
    CI_TRON_TIMEOUT__CONSOLE_ACTIVITY__RETRIES: 1
    CI_TRON_TIMEOUT__OVERALL__MINUTES: 180

    CI_TRON_KERNEL_CMDLINE__LOG_LEVEL: loglevel=6
    CI_TRON_KERNEL_CMDLINE__NO_HASH_POINTERS: no_hash_pointers

    CI_TRON__B2C_ARTIFACT_EXCLUSION: "*.shader_cache,vkd3d-proton.cache*,*.qpa"
    CI_TRON__B2C_IMAGE__IMAGE_UNDER_TEST: "{{ registry.to_local_proxy('${CI_REGISTRY_IMAGE}/jupiter-mesa-${JUPITER_VERSION}:${CI_COMMIT_SHORT_SHA}') }}"

  # Download the content of the `.valve-ci/` folder in the `ci` branch
  before_script:
    - apk add git
    - git clone --depth 1 -b ci ${CI_REPOSITORY_URL} .

# Hardware jobs

.jupiter-test:
  extends:
    - .ci-tron-job
  needs:
    - jupiter-mesa
  variables:
    IMAGE_NAME: jupiter-mesa
    CI_TRON_KERNEL_CMDLINE__B2C_LOGIN_PROXY_REGISTRY: b2c.login="ci-gateway:8010,username=${MUPUF_REGISTRY_USERNAME},password=${MUPUF_REGISTRY_PASSWORD},tls-verify=false"

.test-vkcts:
  extends:
    - .jupiter-test
  variables:
    CI_TRON__B2C_EXEC_CMD: .valve-ci/run-vkcts.sh

.test-vkd3d-proton:
  extends:
    - .jupiter-test
  variables:
    CI_TRON__B2C_EXEC_CMD: .valve-ci/run-vkd3d-proton.sh
    CI_TRON_JOB_SUCCESS_REGEX: 'vkd3d-proton execution: SUCCESS\r$'


# VanGogh

.vangogh-test-valve:
  tags:
    - amdgpu:codename:VANGOGH
    - ci-tron:priority:low
  variables:
    GPU_VERSION: radv-vangogh$GPU_VERSION_SUFFIX
    CI_JOB_CONCURRENCY: 8
    CI_TRON_KERNEL_CMDLINE__DISABLE_IOMMU: amd_iommu=off
    CI_TRON_KERNEL_CMDLINE__GTT_SIZE: amdgpu.gttsize=8128

jupiter-vkcts-vangogh:
  extends:
    - .test-vkcts
    - .vangogh-test-valve

jupiter-vkd3d-proton-vangogh:
  extends:
    - .test-vkd3d-proton
    - .vangogh-test-valve


# Navi21

.navi21-test-valve:
  tags:
    - amdgpu:codename:NAVI21
    - ci-tron:priority:low
  variables:
    GPU_VERSION: radv-navi21$GPU_VERSION_SUFFIX
    CI_JOB_CONCURRENCY: 32

jupiter-vkcts-navi21:
  extends:
    - .test-vkcts
    - .navi21-test-valve

jupiter-vkd3d-proton-navi21:
  extends:
    - .test-vkd3d-proton
    - .navi21-test-valve


# Navi31

.navi31-test-valve:
  tags:
    - amdgpu:codename:NAVI31
    - ci-tron:priority:low
  variables:
    GPU_VERSION: radv-navi31$GPU_VERSION_SUFFIX
    CI_JOB_CONCURRENCY: 32
    RADV_DEBUG: nomeshshader

jupiter-vkcts-navi31:
  extends:
    - .test-vkcts
    - .navi31-test-valve

jupiter-vkd3d-proton-navi31:
  extends:
    - .test-vkd3d-proton
    - .navi31-test-valve
